[build]
  command = "npm run build"
  publish = "dist" # Carpeta de salida del frontend
  functions = "netlify/functions" # Carpeta donde están tus funciones

[functions]
  directory = "netlify/functions"
